os: linux
dist: focal
language: cpp

install:
 - sudo apt update
 - sudo apt install --yes libgtest-dev

jobs:
 include:
  - stage: Coverage
    before_script:
     - sudo apt install --yes gcovr
    script:
     - cmake -B build -DWITH_COVERAGE=1
     - make -C build
     - $TRAVIS_BUILD_DIR/main --filepath $TRAVIS_BUILD_DIR/data/ex.txt --graph ":)" --graph ":(" --bufsize 50
     - curl -Os https://uploader.codecov.io/latest/linux/codecov
     - chmod +x codecov
     - gcovr -e 'gtest/' --html
     - $TRAVIS_BUILD_DIR/codecov -t ${359aa7ea-6ea3-4f92-a92e-adc834cbbf72} -f <(gcovr -e 'gtest/' -x)
